<a href="https://colab.research.google.com/github/OShev-11/Film-Rating-Pandas/blob/main/FilmRating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving ratings.csv to ratings.csv

In [3]:
rating = pd.read_csv('ratings.csv')
rating.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [5]:
def movie_rating(rating):
    if rating <= 2:
          return 'Низкий'
    if 2 < rating <= 4:
          return 'Средний'
    else:
        return 'Высокий'

rating['class'] = rating['rating'].apply(movie_rating)

rating.head(10)

   userId  movieId  rating   timestamp    class
0       1       31     2.5  1260759144  Средний
1       1     1029     3.0  1260759179  Средний
2       1     1061     3.0  1260759182  Средний
3       1     1129     2.0  1260759185   Низкий
4       1     1172     4.0  1260759205  Средний
5       1     1263     2.0  1260759151   Низкий
6       1     1287     2.0  1260759187   Низкий
7       1     1293     2.0  1260759148   Низкий
8       1     1339     3.5  1260759125  Средний
9       1     1343     2.0  1260759131   Низкий